// Generated by CoffeeScript 1.10.0
(function() {
  var app, assert, async, express, expressResponseError, supertest, test;

  expressResponseError = require('../index');

  express = require('express');

  async = require('async');

  assert = require('assert');

  supertest = require('supertest');

  app = new express();

  app.use(expressResponseError());

  app.get('*', function(req, res, next) {
    return res.error(req.query.message || 'no message', req.query.statusCode);
  });

  test = supertest(app);

  describe('middleware', function() {
    return it('should return status code', function(done) {
      return async.forEach([200, 201, 400], function(status, cb) {
        return test.get('/?message=status-' + status + '&statusCode=' + status).expect(status).expect(function(res) {
          return assert.equal(res.body.error, 'status-' + status);
        }).end(cb);
      }, done);
    });
  });

}).call(this);
